# -*- coding: utf-8 -*-
"""PLGA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4ST_T66VOlDpMDrS4lphWu3ugU49xUy
"""

# ============================================================
# PLGA Drug Release ML Pipeline
# Dataset: Bao et al., 2024 (Mendeley Data)
# DOI: https://doi.org/10.17632/zzvtdrcy76.2
# ============================================================

# ============================================================
# PLGA Drug Release ML — Simplified Version
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# ── 1. LOAD DATA ────────────────────────────────────────────
df = pd.read_excel("mp_dataset_processed.xlsx")

# ── 2. CLEAN DATA ───────────────────────────────────────────
df = df.dropna()

# Keep hydrophobic drugs only (domain consistency)
df = df[df["Drug LogP"] > 2]

# Time transformation
df["log_time"] = np.log(df["Time"] + 1)

# Ensure release is in fraction scale (0–1)
df.loc[df["Release"] > 1, "Release"] = df["Release"] / 100

# ── 3. FEATURES ─────────────────────────────────────────────
features = [
    "Drug MW",
    "Drug TPSA",
    "Drug LogP",
    "Polymer MW",
    "LA/GA",
    "Particle Size",
    "Drug Loading Capacity",
    "Drug Encapsulation Efficiency",
    "log_time"
]

X = df[features]
y = df["Release"]

# ── 4. TRAIN MODEL ──────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# ── 5. EVALUATE ─────────────────────────────────────────────
y_pred = model.predict(X_test)

r2   = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae  = mean_absolute_error(y_test, y_pred)

print("\nMODEL PERFORMANCE")
print(f"R2   : {r2:.3f}")
print(f"RMSE : {rmse:.3f}")
print(f"MAE  : {mae:.3f}")

# ── 6. VISUALIZE ────────────────────────────────────────────
plt.figure(figsize=(6,5))

plt.scatter(y_test * 100, y_pred * 100)
plt.plot([0,100], [0,100], 'r--')

plt.xlabel("Actual Release (%)")
plt.ylabel("Predicted Release (%)")
plt.title("Predicted vs Actual Release")

plt.show()